import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Fauni
 */
public class Register_Form extends javax.swing.JFrame {

     db_connection conn = new db_connection();
    Connection con =conn.get_connection();
     
    // Connection con = null;
    
    /**
     * Creates new form Register_Class
     */
    public Register_Form() {
        initComponents();
        
      //****************** show table data after Login ********* //  
        showTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        ID_label = new javax.swing.JLabel();
        Button_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Register");

        username.setForeground(new java.awt.Color(153, 153, 153));
        username.setText(" Username");
        username.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        username.setHighlighter(null);
        username.setName(""); // NOI18N
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
        });
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usernameMousePressed(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameKeyTyped(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 180, 126));
        jButton1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ADD");
        jButton1.setToolTipText("");
        jButton1.setBorder(null);
        jButton1.setFocusPainted(false);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        password.setForeground(new java.awt.Color(153, 153, 153));
        password.setText(" Password");
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleParent(this);

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ID_label.setText("ID");

        Button_delete.setText("Delete");
        Button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ID_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(288, 288, 288))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(username, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(7, 7, 7)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(Button_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID_label))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(Button_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        username.getAccessibleContext().setAccessibleName("");
        username.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        PreparedStatement pst_check;
        
        
        ResultSet rs;
        
        String uname = username.getText();
        String upass = new String(password.getPassword());
       
        String Check_query = "Select * from `sample` where `username` =? ";

         try {
                    
             
                    
                 pst_check = con.prepareStatement(Check_query);
                 pst_check.setString(1, uname);
                                 
                 rs = pst_check.executeQuery();
                 
                 if(rs.next())
                 {
                 JOptionPane.showMessageDialog(null,"already Exist!!");
                 }
                 
                           
            // ********** end of check if data is already exist! *****************
                 
               //************** Start check if jTextfield are Empty *********************  
                 
                 else if(uname.trim().equals("") || upass.trim().equals(""))
                 
                 {
                 JOptionPane.showMessageDialog(null,"Please Fill up the fields!");
                 
                 }
                //******************  End of check empty fields       ******************
                 
            else{
                     
           // ************************ Insert data *******************************
                  
             String query = "insert into sample (username,password) values (?,?)";
            //con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/test", "root" ,"");
            try (PreparedStatement pst = con.prepareStatement(query)) {
          
               
                pst.setString(1, username.getText());
                pst.setString(2, password.getText());
               
            
                
                pst.execute();
                
                // *** show new add data in table *****
                    showTableData();
                //************************************
            }
                  JOptionPane.showMessageDialog(null,"Record Save!");
            }
                
                
                }
                  
                  
            
       // }
            catch(Exception e){
                e.printStackTrace();
                
            
            }
              
        
    }//GEN-LAST:event_jButton1ActionPerformed
    //**************** end of insert ******************************************** //
    
    
        //********** -- Start -- function to show data on the table ********
    
        public final void showTableData(){
            
           PreparedStatement pst;
           ResultSet rs; 
           
      //  DefaultTableModel table = new DefaultTableModel();
   DefaultTableModel table = new DefaultTableModel(new String[]{"Id", "Username", "password"}, 0);
  
            try {
                String sql="SELECT * FROM sample";
                pst = con.prepareStatement(sql);  
                rs = pst.executeQuery(sql);
                
             //   String query = "Select * from sample";
               // pst = con.prepareStatement(query);     
              //  rs = pst.executeQuery();
                
                
                 while(rs.next())
                    {
                    String ID = rs.getString("id");
                    String uname = rs.getString("username");
                    String upass = rs.getString("password");
                     table.addRow(new Object[]{ ID, uname, upass});
                       }
            
             jTable1.setModel(table);
                
            }
            catch (Exception e) {
            }

               
            
        }
    //********** -- END -- function to show data on the table ********    
    
    
    
    
    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseClicked
            // TODO add your handling code here:
        username.setText("");
       
    }//GEN-LAST:event_usernameMouseClicked

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
                // TODO add your handling code here:
       
        password.setText("");
    }//GEN-LAST:event_passwordMouseClicked

    private void usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_usernameKeyTyped

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
      // TODO add your handling code here:
    }//GEN-LAST:event_usernameFocusGained

    private void usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyPressed
       // TODO add your handling code here:
    }//GEN-LAST:event_usernameKeyPressed

    private void usernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMousePressed
         // TODO add your handling code here:
    }//GEN-LAST:event_usernameMousePressed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        
            password.setText("Password");  
         username.setText("Username");
          
        
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //*********** on mouse click display the select row ************
        
        int selected_row =jTable1.getSelectedRow();
          DefaultTableModel table = (DefaultTableModel)jTable1.getModel();
          ID_label.setText(table.getValueAt(selected_row, 0 ).toString());
          username.setText(table.getValueAt(selected_row, 1 ).toString());
          password.setText(table.getValueAt(selected_row, 2 ).toString());
          
       
          
          
          
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //**************** Start function for update button ****************
        
        int i =jTable1.getSelectedRow();
        DefaultTableModel table = (DefaultTableModel)jTable1.getModel();
       // String upass = new String(password.getPassword());
        if(i>0){
            table.setValueAt(ID_label.getText(), i ,0);
            table.setValueAt(username.getText(), i ,1);
            table.setValueAt(password.getPassword(), i ,2);
             
        }
        
        
           // ************************ Update data *******************************
           try {
               
             PreparedStatement pst_update,pst_check;  
             ResultSet rs;
             
             String id = ID_label.getText();
             String uname = username.getText();
             String upass = new String(password.getPassword());
             
             //**************  check before update dating *****************
            String Check_query = "Select * from `sample` where `username` =? ";
               pst_check = con.prepareStatement(Check_query);
                 pst_check.setString(1, uname);
                                 
                 rs = pst_check.executeQuery();
                 
                 if(rs.next())
                 {
                 JOptionPane.showMessageDialog(null,"already Exist!!");
                 }
                 
                           
            // ********** end of check if data is already exist! *****************
             
                 else{
             
             
              
             
             String query = "Update sample set username ='"+uname+"' , password='"+upass+"' where id='"+id+"' ";
            //con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/test", "root" ,"");
             pst_update = con.prepareStatement(query) ;
          
               
               // pst_update.setString(1, username.getText());
                //pst_update.setString(2, password.getText());
               
            
                
                pst_update.execute();
              JOptionPane.showMessageDialog(null,"Record Updated!");
                 }
               
                
                // *** show new add data in table *****
                    showTableData();
                //************************************
            
                  
            
        }
    
catch (Exception e) {
    
    //JOptionPane.showMessageDialog(null,"Not Updated!");
        }

               
        
          //**************** End function for update button ****************
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_deleteActionPerformed
       
        //******* Delete data from table **************
        
        
         //**************** Start function for Delete button ****************
        
        int i =jTable1.getSelectedRow();
        DefaultTableModel table = (DefaultTableModel)jTable1.getModel();
       // String upass = new String(password.getPassword());
        if(i>0){
            table.setValueAt(ID_label.getText(), i ,0);
            table.setValueAt(username.getText(), i ,1);
            table.setValueAt(password.getPassword(), i ,2);
             
        }
        
        
           // ************************ Delete data *******************************
           try {
               
             PreparedStatement pst_Delete;  
       
             
             String id = ID_label.getText();
               
             String Delete_query = "Delete from sample where id='"+id+"'";
             pst_Delete = con.prepareStatement(Delete_query);
          
             pst_Delete.executeUpdate();
              
             JOptionPane.showMessageDialog(null,"Record Deleted!");
             // *** show new add data in table *****
                     showTableData();
                //************************************
            
             
                 }
 
catch ( SQLException | HeadlessException e) {
    
    //JOptionPane.showMessageDialog(null,"Not Updated!");
        }
        
        
        
    }//GEN-LAST:event_Button_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
               new Register_Form().setVisible(true);
               
             
            }
        });
    }
     

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_delete;
    private javax.swing.JLabel ID_label;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
